package constant

const (
	KubeKindConfigMap                      = "ConfigMap"
	KubeKindControllerRevision             = "ControllerRevision"
	KubeKindCronJob                        = "CronJob"
	KubeKindCertificateSigningRequest      = "CertificateSigningRequest"
	KubeKindClusterRole                    = "ClusterRole"
	KubeKindClusterRoleBinding             = "ClusterRoleBinding"
	KubeKindCSIDriver                      = "CSIDriver"
	KubeKindCSINode                        = "CSINode"
	KubeKindComponentStatus                = "ComponentStatus"
	KubeKindDaemonSet                      = "DaemonSet"
	KubeKindDeployment                     = "Deployment"
	KubeKindEndpoints                      = "Endpoints"
	KubeKindEvent                          = "Event"
	KubeKindEndpointSlice                  = "EndpointSlice"
	KubeKindFlowSchema                     = "FlowSchema"
	KubeKindHorizontalPodAutoscaler        = "HorizontalPodAutoscaler"
	KubeKindIngress                        = "Ingress"
	KubeKindIngressClass                   = "IngressClass"
	KubeKindJob                            = "Job"
	KubeKindLease                          = "Lease"
	KubeKindLimitRange                     = "LimitRange"
	KubeKindMutatingWebhookConfiguration   = "MutatingWebhookConfiguration"
	KubeKindNamespace                      = "Namespace"
	KubeKindNode                           = "Node"
	KubeKindNetworkPolicy                  = "NetworkPolicy"
	KubeKindPersistentVolume               = "PersistentVolume"
	KubeKindPersistentVolumeClaim          = "PersistentVolumeClaim"
	KubeKindPod                            = "Pod"
	KubeKindPodTemplate                    = "PodTemplate"
	KubeKindPodSecurityPolicy              = "PodSecurityPolicy"
	KubeKindPriorityLevelConfiguration     = "PriorityLevelConfiguration"
	KubeKindPriorityClass                  = "PriorityClass"
	KubeKindPodDisruptionBudget            = "PodDisruptionBudget"
	KubeKindReplicaSet                     = "ReplicaSet"
	KubeKindReplicationController          = "ReplicationController"
	KubeKindResourceQuota                  = "ResourceQuota"
	KubeKindRuntimeClass                   = "RuntimeClass"
	KubeKindRole                           = "Role"
	KubeKindRoleBinding                    = "RoleBinding"
	KubeKindRangeAllocation                = "RangeAllocation"
	KubeKindStatefulSet                    = "StatefulSet"
	KubeKindSecret                         = "Secret"
	KubeKindService                        = "Service"
	KubeKindServiceAccount                 = "ServiceAccount"
	KubeKindStorageClass                   = "StorageClass"
	KubeKindValidatingWebhookConfiguration = "ValidatingWebhookConfiguration"
	KubeKindVolumeAttachment               = "VolumeAttachment"
)

const (
	KubeRootKey         = "registry"
	KubeRootPrefix      = "/" + KubeRootKey + "/"
	KubeNamespacePrefix = KubeRootPrefix + "namespaces" + "/"
)
