apiVersion: v1
kind: Secret
metadata:
  name: influxdb
  namespace: unique
type: Opaque
data:
  influxdb-user: "root"
  influxdb-password: "12345678"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: unit-test
type: Opaque
data:
  influxdb-user: "root"
  influxdb-password: "12345678"
---
apiVersion: v1
kind: Secret
metadata:
  name: exclude-me-secret
  namespace: unique
type: Opaque
data:
  influxdb-user: "test"
  influxdb-password: "test"
